vim.keymap.set('c', ';bb', '/home/si/.local/bin<cr>', { noremap = true, silent = true, desc = '~/.local/bin' })
vim.keymap.set('n', '<localleader><leader>bb', '<cmd>Explore /home/si/.local/bin<cr>', { noremap = true, silent = true, desc = '~/.local/bin' })
vim.keymap.set('n', '<localleader><localleader>bb', function() require('mini.files').open('/home/si/.local/bin') end, { noremap = true, silent = true, desc = '~/.local/bin' })
vim.keymap.set('c', ';bs', '/home/si/.local/bin/statusbar<cr>', { noremap = true, silent = true, desc = '~/.local/bin/statusbar' })
vim.keymap.set('n', '<localleader><leader>bs', '<cmd>Explore /home/si/.local/bin/statusbar<cr>', { noremap = true, silent = true, desc = '~/.local/bin/statusbar' })
vim.keymap.set('n', '<localleader><localleader>bs', function() require('mini.files').open('/home/si/.local/bin/statusbar') end, { noremap = true, silent = true, desc = '~/.local/bin/statusbar' })
vim.keymap.set('c', ';btt', '/home/si/.local/bin/task/taskwarrior-tui<cr>', { noremap = true, silent = true, desc = '~/.local/bin/task/taskwarrior-tui' })
vim.keymap.set('n', '<localleader><leader>btt', '<cmd>Explore /home/si/.local/bin/task/taskwarrior-tui<cr>', { noremap = true, silent = true, desc = '~/.local/bin/task/taskwarrior-tui' })
vim.keymap.set('n', '<localleader><localleader>btt', function() require('mini.files').open('/home/si/.local/bin/task/taskwarrior-tui') end, { noremap = true, silent = true, desc = '~/.local/bin/task/taskwarrior-tui' })
vim.keymap.set('c', ';cab', '/home/si/.config/abook<cr>', { noremap = true, silent = true, desc = '~/.config/abook' })
vim.keymap.set('n', '<localleader><leader>cab', '<cmd>Explore /home/si/.config/abook<cr>', { noremap = true, silent = true, desc = '~/.config/abook' })
vim.keymap.set('n', '<localleader><localleader>cab', function() require('mini.files').open('/home/si/.config/abook') end, { noremap = true, silent = true, desc = '~/.config/abook' })
vim.keymap.set('c', ';cac', '/home/si/.cache<cr>', { noremap = true, silent = true, desc = '~/.cache' })
vim.keymap.set('n', '<localleader><leader>cac', '<cmd>Explore /home/si/.cache<cr>', { noremap = true, silent = true, desc = '~/.cache' })
vim.keymap.set('n', '<localleader><localleader>cac', function() require('mini.files').open('/home/si/.cache') end, { noremap = true, silent = true, desc = '~/.cache' })
vim.keymap.set('c', ';cbc', '/home/si/.config/bash<cr>', { noremap = true, silent = true, desc = '~/.config/bash' })
vim.keymap.set('n', '<localleader><leader>cbc', '<cmd>Explore /home/si/.config/bash<cr>', { noremap = true, silent = true, desc = '~/.config/bash' })
vim.keymap.set('n', '<localleader><localleader>cbc', function() require('mini.files').open('/home/si/.config/bash') end, { noremap = true, silent = true, desc = '~/.config/bash' })
vim.keymap.set('c', ';cdb', '/home/si/.local/src/suckless/dwmblocks<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/dwmblocks' })
vim.keymap.set('n', '<localleader><leader>cdb', '<cmd>Explore /home/si/.local/src/suckless/dwmblocks<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/dwmblocks' })
vim.keymap.set('n', '<localleader><localleader>cdb', function() require('mini.files').open('/home/si/.local/src/suckless/dwmblocks') end, { noremap = true, silent = true, desc = '~/.local/src/suckless/dwmblocks' })
vim.keymap.set('c', ';cdm', '/home/si/.local/src/suckless/dmenu<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/dmenu' })
vim.keymap.set('n', '<localleader><leader>cdm', '<cmd>Explore /home/si/.local/src/suckless/dmenu<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/dmenu' })
vim.keymap.set('n', '<localleader><localleader>cdm', function() require('mini.files').open('/home/si/.local/src/suckless/dmenu') end, { noremap = true, silent = true, desc = '~/.local/src/suckless/dmenu' })
vim.keymap.set('c', ';cdw', '/home/si/.local/src/suckless/dwm<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/dwm' })
vim.keymap.set('n', '<localleader><leader>cdw', '<cmd>Explore /home/si/.local/src/suckless/dwm<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/dwm' })
vim.keymap.set('n', '<localleader><localleader>cdw', function() require('mini.files').open('/home/si/.local/src/suckless/dwm') end, { noremap = true, silent = true, desc = '~/.local/src/suckless/dwm' })
vim.keymap.set('c', ';cfg', '/home/si/.config<cr>', { noremap = true, silent = true, desc = '~/.config' })
vim.keymap.set('n', '<localleader><leader>cfg', '<cmd>Explore /home/si/.config<cr>', { noremap = true, silent = true, desc = '~/.config' })
vim.keymap.set('n', '<localleader><localleader>cfg', function() require('mini.files').open('/home/si/.config') end, { noremap = true, silent = true, desc = '~/.config' })
vim.keymap.set('c', ';cfx', '/home/si/.config/firefox<cr>', { noremap = true, silent = true, desc = '~/.config/firefox' })
vim.keymap.set('n', '<localleader><leader>cfx', '<cmd>Explore /home/si/.config/firefox<cr>', { noremap = true, silent = true, desc = '~/.config/firefox' })
vim.keymap.set('n', '<localleader><localleader>cfx', function() require('mini.files').open('/home/si/.config/firefox') end, { noremap = true, silent = true, desc = '~/.config/firefox' })
vim.keymap.set('c', ';clf', '/home/si/.config/lf<cr>', { noremap = true, silent = true, desc = '~/.config/lf' })
vim.keymap.set('n', '<localleader><leader>clf', '<cmd>Explore /home/si/.config/lf<cr>', { noremap = true, silent = true, desc = '~/.config/lf' })
vim.keymap.set('n', '<localleader><localleader>clf', function() require('mini.files').open('/home/si/.config/lf') end, { noremap = true, silent = true, desc = '~/.config/lf' })
vim.keymap.set('c', ';clv', '/home/si/.config/LazyVim<cr>', { noremap = true, silent = true, desc = '~/.config/LazyVim' })
vim.keymap.set('n', '<localleader><leader>clv', '<cmd>Explore /home/si/.config/LazyVim<cr>', { noremap = true, silent = true, desc = '~/.config/LazyVim' })
vim.keymap.set('n', '<localleader><localleader>clv', function() require('mini.files').open('/home/si/.config/LazyVim') end, { noremap = true, silent = true, desc = '~/.config/LazyVim' })
vim.keymap.set('c', ';cmd', '/home/si/.config/mpd<cr>', { noremap = true, silent = true, desc = '~/.config/mpd' })
vim.keymap.set('n', '<localleader><leader>cmd', '<cmd>Explore /home/si/.config/mpd<cr>', { noremap = true, silent = true, desc = '~/.config/mpd' })
vim.keymap.set('n', '<localleader><localleader>cmd', function() require('mini.files').open('/home/si/.config/mpd') end, { noremap = true, silent = true, desc = '~/.config/mpd' })
vim.keymap.set('c', ';cmv', '/home/si/.config/mpv<cr>', { noremap = true, silent = true, desc = '~/.config/mpv' })
vim.keymap.set('n', '<localleader><leader>cmv', '<cmd>Explore /home/si/.config/mpv<cr>', { noremap = true, silent = true, desc = '~/.config/mpv' })
vim.keymap.set('n', '<localleader><localleader>cmv', function() require('mini.files').open('/home/si/.config/mpv') end, { noremap = true, silent = true, desc = '~/.config/mpv' })
vim.keymap.set('c', ';cmw', '/home/si/.config/mutt<cr>', { noremap = true, silent = true, desc = '~/.config/mutt' })
vim.keymap.set('n', '<localleader><leader>cmw', '<cmd>Explore /home/si/.config/mutt<cr>', { noremap = true, silent = true, desc = '~/.config/mutt' })
vim.keymap.set('n', '<localleader><localleader>cmw', function() require('mini.files').open('/home/si/.config/mutt') end, { noremap = true, silent = true, desc = '~/.config/mutt' })
vim.keymap.set('c', ';cnc', '/home/si/.config/NvChad<cr>', { noremap = true, silent = true, desc = '~/.config/NvChad' })
vim.keymap.set('n', '<localleader><leader>cnc', '<cmd>Explore /home/si/.config/NvChad<cr>', { noremap = true, silent = true, desc = '~/.config/NvChad' })
vim.keymap.set('n', '<localleader><localleader>cnc', function() require('mini.files').open('/home/si/.config/NvChad') end, { noremap = true, silent = true, desc = '~/.config/NvChad' })
vim.keymap.set('c', ';cnp', '/home/si/.config/ncmpcpp<cr>', { noremap = true, silent = true, desc = '~/.config/ncmpcpp' })
vim.keymap.set('n', '<localleader><leader>cnp', '<cmd>Explore /home/si/.config/ncmpcpp<cr>', { noremap = true, silent = true, desc = '~/.config/ncmpcpp' })
vim.keymap.set('n', '<localleader><localleader>cnp', function() require('mini.files').open('/home/si/.config/ncmpcpp') end, { noremap = true, silent = true, desc = '~/.config/ncmpcpp' })
vim.keymap.set('c', ';cns', '/home/si/.config/newsboat<cr>', { noremap = true, silent = true, desc = '~/.config/newsboat' })
vim.keymap.set('n', '<localleader><leader>cns', '<cmd>Explore /home/si/.config/newsboat<cr>', { noremap = true, silent = true, desc = '~/.config/newsboat' })
vim.keymap.set('n', '<localleader><localleader>cns', function() require('mini.files').open('/home/si/.config/newsboat') end, { noremap = true, silent = true, desc = '~/.config/newsboat' })
vim.keymap.set('c', ';cnv', '/home/si/.config/nvim/lua/thesiahxyz<cr>', { noremap = true, silent = true, desc = '~/.config/nvim/lua/thesiahxyz' })
vim.keymap.set('n', '<localleader><leader>cnv', '<cmd>Explore /home/si/.config/nvim/lua/thesiahxyz<cr>', { noremap = true, silent = true, desc = '~/.config/nvim/lua/thesiahxyz' })
vim.keymap.set('n', '<localleader><localleader>cnv', function() require('mini.files').open('/home/si/.config/nvim/lua/thesiahxyz') end, { noremap = true, silent = true, desc = '~/.config/nvim/lua/thesiahxyz' })
vim.keymap.set('c', ';cr', '/home/si/.local/bin/cron<cr>', { noremap = true, silent = true, desc = '~/.local/bin/cron' })
vim.keymap.set('n', '<localleader><leader>cr', '<cmd>Explore /home/si/.local/bin/cron<cr>', { noremap = true, silent = true, desc = '~/.local/bin/cron' })
vim.keymap.set('n', '<localleader><localleader>cr', function() require('mini.files').open('/home/si/.local/bin/cron') end, { noremap = true, silent = true, desc = '~/.local/bin/cron' })
vim.keymap.set('c', ';cse', '/home/si/.config/sesh<cr>', { noremap = true, silent = true, desc = '~/.config/sesh' })
vim.keymap.set('n', '<localleader><leader>cse', '<cmd>Explore /home/si/.config/sesh<cr>', { noremap = true, silent = true, desc = '~/.config/sesh' })
vim.keymap.set('n', '<localleader><localleader>cse', function() require('mini.files').open('/home/si/.config/sesh') end, { noremap = true, silent = true, desc = '~/.config/sesh' })
vim.keymap.set('c', ';csh', '/home/si/.config/shell<cr>', { noremap = true, silent = true, desc = '~/.config/shell' })
vim.keymap.set('n', '<localleader><leader>csh', '<cmd>Explore /home/si/.config/shell<cr>', { noremap = true, silent = true, desc = '~/.config/shell' })
vim.keymap.set('n', '<localleader><localleader>csh', function() require('mini.files').open('/home/si/.config/shell') end, { noremap = true, silent = true, desc = '~/.config/shell' })
vim.keymap.set('c', ';csl', '/home/si/.local/src/suckless/slock<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/slock' })
vim.keymap.set('n', '<localleader><leader>csl', '<cmd>Explore /home/si/.local/src/suckless/slock<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/slock' })
vim.keymap.set('n', '<localleader><localleader>csl', function() require('mini.files').open('/home/si/.local/src/suckless/slock') end, { noremap = true, silent = true, desc = '~/.local/src/suckless/slock' })
vim.keymap.set('c', ';cst', '/home/si/.local/src/suckless/st<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/st' })
vim.keymap.set('n', '<localleader><leader>cst', '<cmd>Explore /home/si/.local/src/suckless/st<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/st' })
vim.keymap.set('n', '<localleader><localleader>cst', function() require('mini.files').open('/home/si/.local/src/suckless/st') end, { noremap = true, silent = true, desc = '~/.local/src/suckless/st' })
vim.keymap.set('c', ';ctd', '/home/si/.config/transmission-daemon<cr>', { noremap = true, silent = true, desc = '~/.config/transmission-daemon' })
vim.keymap.set('n', '<localleader><leader>ctd', '<cmd>Explore /home/si/.config/transmission-daemon<cr>', { noremap = true, silent = true, desc = '~/.config/transmission-daemon' })
vim.keymap.set('n', '<localleader><localleader>ctd', function() require('mini.files').open('/home/si/.config/transmission-daemon') end, { noremap = true, silent = true, desc = '~/.config/transmission-daemon' })
vim.keymap.set('c', ';ctp', '/home/si/.config/tmux/plugins<cr>', { noremap = true, silent = true, desc = '~/.config/tmux/plugins' })
vim.keymap.set('n', '<localleader><leader>ctp', '<cmd>Explore /home/si/.config/tmux/plugins<cr>', { noremap = true, silent = true, desc = '~/.config/tmux/plugins' })
vim.keymap.set('n', '<localleader><localleader>ctp', function() require('mini.files').open('/home/si/.config/tmux/plugins') end, { noremap = true, silent = true, desc = '~/.config/tmux/plugins' })
vim.keymap.set('c', ';cts', '/home/si/.config/TheSiahxyz/lua/thesiahxyz<cr>', { noremap = true, silent = true, desc = '~/.config/TheSiahxyz/lua/thesiahxyz' })
vim.keymap.set('n', '<localleader><leader>cts', '<cmd>Explore /home/si/.config/TheSiahxyz/lua/thesiahxyz<cr>', { noremap = true, silent = true, desc = '~/.config/TheSiahxyz/lua/thesiahxyz' })
vim.keymap.set('n', '<localleader><localleader>cts', function() require('mini.files').open('/home/si/.config/TheSiahxyz/lua/thesiahxyz') end, { noremap = true, silent = true, desc = '~/.config/TheSiahxyz/lua/thesiahxyz' })
vim.keymap.set('c', ';cvc', '/home/si/.config/vim<cr>', { noremap = true, silent = true, desc = '~/.config/vim' })
vim.keymap.set('n', '<localleader><leader>cvc', '<cmd>Explore /home/si/.config/vim<cr>', { noremap = true, silent = true, desc = '~/.config/vim' })
vim.keymap.set('n', '<localleader><localleader>cvc', function() require('mini.files').open('/home/si/.config/vim') end, { noremap = true, silent = true, desc = '~/.config/vim' })
vim.keymap.set('c', ';cvp', '/home/si/.config/openvpn<cr>', { noremap = true, silent = true, desc = '~/.config/openvpn' })
vim.keymap.set('n', '<localleader><leader>cvp', '<cmd>Explore /home/si/.config/openvpn<cr>', { noremap = true, silent = true, desc = '~/.config/openvpn' })
vim.keymap.set('n', '<localleader><localleader>cvp', function() require('mini.files').open('/home/si/.config/openvpn') end, { noremap = true, silent = true, desc = '~/.config/openvpn' })
vim.keymap.set('c', ';cxc', '/home/si/.config/x11<cr>', { noremap = true, silent = true, desc = '~/.config/x11' })
vim.keymap.set('n', '<localleader><leader>cxc', '<cmd>Explore /home/si/.config/x11<cr>', { noremap = true, silent = true, desc = '~/.config/x11' })
vim.keymap.set('n', '<localleader><localleader>cxc', function() require('mini.files').open('/home/si/.config/x11') end, { noremap = true, silent = true, desc = '~/.config/x11' })
vim.keymap.set('c', ';cyv', '/home/si/.config/youtube-viewer<cr>', { noremap = true, silent = true, desc = '~/.config/youtube-viewer' })
vim.keymap.set('n', '<localleader><leader>cyv', '<cmd>Explore /home/si/.config/youtube-viewer<cr>', { noremap = true, silent = true, desc = '~/.config/youtube-viewer' })
vim.keymap.set('n', '<localleader><localleader>cyv', function() require('mini.files').open('/home/si/.config/youtube-viewer') end, { noremap = true, silent = true, desc = '~/.config/youtube-viewer' })
vim.keymap.set('c', ';czc', '/home/si/.config/zsh<cr>', { noremap = true, silent = true, desc = '~/.config/zsh' })
vim.keymap.set('n', '<localleader><leader>czc', '<cmd>Explore /home/si/.config/zsh<cr>', { noremap = true, silent = true, desc = '~/.config/zsh' })
vim.keymap.set('n', '<localleader><localleader>czc', function() require('mini.files').open('/home/si/.config/zsh') end, { noremap = true, silent = true, desc = '~/.config/zsh' })
vim.keymap.set('c', ';dot', '/home/si/.dotfiles<cr>', { noremap = true, silent = true, desc = '~/.dotfiles' })
vim.keymap.set('n', '<localleader><leader>dot', '<cmd>Explore /home/si/.dotfiles<cr>', { noremap = true, silent = true, desc = '~/.dotfiles' })
vim.keymap.set('n', '<localleader><localleader>dot', function() require('mini.files').open('/home/si/.dotfiles') end, { noremap = true, silent = true, desc = '~/.dotfiles' })
vim.keymap.set('c', ';Esm', '/etc/samba<cr>', { noremap = true, silent = true, desc = '/etc/samba' })
vim.keymap.set('n', '<localleader><leader>Esm', '<cmd>Explore /etc/samba<cr>', { noremap = true, silent = true, desc = '/etc/samba' })
vim.keymap.set('n', '<localleader><localleader>Esm', function() require('mini.files').open('/etc/samba') end, { noremap = true, silent = true, desc = '/etc/samba' })
vim.keymap.set('c', ';Esv', '/etc/runit/sv<cr>', { noremap = true, silent = true, desc = '/etc/runit/sv' })
vim.keymap.set('n', '<localleader><leader>Esv', '<cmd>Explore /etc/runit/sv<cr>', { noremap = true, silent = true, desc = '/etc/runit/sv' })
vim.keymap.set('n', '<localleader><localleader>Esv', function() require('mini.files').open('/etc/runit/sv') end, { noremap = true, silent = true, desc = '/etc/runit/sv' })
vim.keymap.set('c', ';gdc', '/home/si/Documents<cr>', { noremap = true, silent = true, desc = '~/Documents' })
vim.keymap.set('n', '<localleader><leader>gdc', '<cmd>Explore /home/si/Documents<cr>', { noremap = true, silent = true, desc = '~/Documents' })
vim.keymap.set('n', '<localleader><localleader>gdc', function() require('mini.files').open('/home/si/Documents') end, { noremap = true, silent = true, desc = '~/Documents' })
vim.keymap.set('c', ';gdk', '/home/si/Desktop<cr>', { noremap = true, silent = true, desc = '~/Desktop' })
vim.keymap.set('n', '<localleader><leader>gdk', '<cmd>Explore /home/si/Desktop<cr>', { noremap = true, silent = true, desc = '~/Desktop' })
vim.keymap.set('n', '<localleader><localleader>gdk', function() require('mini.files').open('/home/si/Desktop') end, { noremap = true, silent = true, desc = '~/Desktop' })
vim.keymap.set('c', ';gdn', '/home/si/Downloads<cr>', { noremap = true, silent = true, desc = '~/Downloads' })
vim.keymap.set('n', '<localleader><leader>gdn', '<cmd>Explore /home/si/Downloads<cr>', { noremap = true, silent = true, desc = '~/Downloads' })
vim.keymap.set('n', '<localleader><localleader>gdn', function() require('mini.files').open('/home/si/Downloads') end, { noremap = true, silent = true, desc = '~/Downloads' })
vim.keymap.set('c', ';gfx', '/home/si/.mozilla/firefox/si.default<cr>', { noremap = true, silent = true, desc = '~/.mozilla/firefox/si.default' })
vim.keymap.set('n', '<localleader><leader>gfx', '<cmd>Explore /home/si/.mozilla/firefox/si.default<cr>', { noremap = true, silent = true, desc = '~/.mozilla/firefox/si.default' })
vim.keymap.set('n', '<localleader><localleader>gfx', function() require('mini.files').open('/home/si/.mozilla/firefox/si.default') end, { noremap = true, silent = true, desc = '~/.mozilla/firefox/si.default' })
vim.keymap.set('c', ';gmu', '/home/si/Music<cr>', { noremap = true, silent = true, desc = '~/Music' })
vim.keymap.set('n', '<localleader><leader>gmu', '<cmd>Explore /home/si/Music<cr>', { noremap = true, silent = true, desc = '~/Music' })
vim.keymap.set('n', '<localleader><localleader>gmu', function() require('mini.files').open('/home/si/Music') end, { noremap = true, silent = true, desc = '~/Music' })
vim.keymap.set('c', ';gpb', '/home/si/Public<cr>', { noremap = true, silent = true, desc = '~/Public' })
vim.keymap.set('n', '<localleader><leader>gpb', '<cmd>Explore /home/si/Public<cr>', { noremap = true, silent = true, desc = '~/Public' })
vim.keymap.set('n', '<localleader><localleader>gpb', function() require('mini.files').open('/home/si/Public') end, { noremap = true, silent = true, desc = '~/Public' })
vim.keymap.set('c', ';gpp', '/home/si/Pictures<cr>', { noremap = true, silent = true, desc = '~/Pictures' })
vim.keymap.set('n', '<localleader><leader>gpp', '<cmd>Explore /home/si/Pictures<cr>', { noremap = true, silent = true, desc = '~/Pictures' })
vim.keymap.set('n', '<localleader><localleader>gpp', function() require('mini.files').open('/home/si/Pictures') end, { noremap = true, silent = true, desc = '~/Pictures' })
vim.keymap.set('c', ';gpv', '/home/si/Private<cr>', { noremap = true, silent = true, desc = '~/Private' })
vim.keymap.set('n', '<localleader><leader>gpv', '<cmd>Explore /home/si/Private<cr>', { noremap = true, silent = true, desc = '~/Private' })
vim.keymap.set('n', '<localleader><localleader>gpv', function() require('mini.files').open('/home/si/Private') end, { noremap = true, silent = true, desc = '~/Private' })
vim.keymap.set('c', ';grr', '/home/si/Pictures/resources<cr>', { noremap = true, silent = true, desc = '~/Pictures/resources' })
vim.keymap.set('n', '<localleader><leader>grr', '<cmd>Explore /home/si/Pictures/resources<cr>', { noremap = true, silent = true, desc = '~/Pictures/resources' })
vim.keymap.set('n', '<localleader><localleader>grr', function() require('mini.files').open('/home/si/Pictures/resources') end, { noremap = true, silent = true, desc = '~/Pictures/resources' })
vim.keymap.set('c', ';gtc', '/home/si/Torrents/complete<cr>', { noremap = true, silent = true, desc = '~/Torrents/complete' })
vim.keymap.set('n', '<localleader><leader>gtc', '<cmd>Explore /home/si/Torrents/complete<cr>', { noremap = true, silent = true, desc = '~/Torrents/complete' })
vim.keymap.set('n', '<localleader><localleader>gtc', function() require('mini.files').open('/home/si/Torrents/complete') end, { noremap = true, silent = true, desc = '~/Torrents/complete' })
vim.keymap.set('c', ';gti', '/home/si/Torrents/incomplete<cr>', { noremap = true, silent = true, desc = '~/Torrents/incomplete' })
vim.keymap.set('n', '<localleader><leader>gti', '<cmd>Explore /home/si/Torrents/incomplete<cr>', { noremap = true, silent = true, desc = '~/Torrents/incomplete' })
vim.keymap.set('n', '<localleader><localleader>gti', function() require('mini.files').open('/home/si/Torrents/incomplete') end, { noremap = true, silent = true, desc = '~/Torrents/incomplete' })
vim.keymap.set('c', ';gtt', '/home/si/Torrents<cr>', { noremap = true, silent = true, desc = '~/Torrents' })
vim.keymap.set('n', '<localleader><leader>gtt', '<cmd>Explore /home/si/Torrents<cr>', { noremap = true, silent = true, desc = '~/Torrents' })
vim.keymap.set('n', '<localleader><localleader>gtt', function() require('mini.files').open('/home/si/Torrents') end, { noremap = true, silent = true, desc = '~/Torrents' })
vim.keymap.set('c', ';gvv', '/home/si/Videos<cr>', { noremap = true, silent = true, desc = '~/Videos' })
vim.keymap.set('n', '<localleader><leader>gvv', '<cmd>Explore /home/si/Videos<cr>', { noremap = true, silent = true, desc = '~/Videos' })
vim.keymap.set('n', '<localleader><localleader>gvv', function() require('mini.files').open('/home/si/Videos') end, { noremap = true, silent = true, desc = '~/Videos' })
vim.keymap.set('c', ';gvy', '/home/si/Videos/Youtube<cr>', { noremap = true, silent = true, desc = '~/Videos/Youtube' })
vim.keymap.set('n', '<localleader><leader>gvy', '<cmd>Explore /home/si/Videos/Youtube<cr>', { noremap = true, silent = true, desc = '~/Videos/Youtube' })
vim.keymap.set('n', '<localleader><localleader>gvy', function() require('mini.files').open('/home/si/Videos/Youtube') end, { noremap = true, silent = true, desc = '~/Videos/Youtube' })
vim.keymap.set('c', ';gwf', '/home/si/.librewolf/si.default<cr>', { noremap = true, silent = true, desc = '~/.librewolf/si.default' })
vim.keymap.set('n', '<localleader><leader>gwf', '<cmd>Explore /home/si/.librewolf/si.default<cr>', { noremap = true, silent = true, desc = '~/.librewolf/si.default' })
vim.keymap.set('n', '<localleader><localleader>gwf', function() require('mini.files').open('/home/si/.librewolf/si.default') end, { noremap = true, silent = true, desc = '~/.librewolf/si.default' })
vim.keymap.set('c', ';gwo', '/home/si/Desktop/Work<cr>', { noremap = true, silent = true, desc = '~/Desktop/Work' })
vim.keymap.set('n', '<localleader><leader>gwo', '<cmd>Explore /home/si/Desktop/Work<cr>', { noremap = true, silent = true, desc = '~/Desktop/Work' })
vim.keymap.set('n', '<localleader><localleader>gwo', function() require('mini.files').open('/home/si/Desktop/Work') end, { noremap = true, silent = true, desc = '~/Desktop/Work' })
vim.keymap.set('c', ';gww', '/home/si/Pictures/wallpaper<cr>', { noremap = true, silent = true, desc = '~/Pictures/wallpaper' })
vim.keymap.set('n', '<localleader><leader>gww', '<cmd>Explore /home/si/Pictures/wallpaper<cr>', { noremap = true, silent = true, desc = '~/Pictures/wallpaper' })
vim.keymap.set('n', '<localleader><localleader>gww', function() require('mini.files').open('/home/si/Pictures/wallpaper') end, { noremap = true, silent = true, desc = '~/Pictures/wallpaper' })
vim.keymap.set('c', ';Hbk', '/mnt/second/backup<cr>', { noremap = true, silent = true, desc = '/mnt/second/backup' })
vim.keymap.set('n', '<localleader><leader>Hbk', '<cmd>Explore /mnt/second/backup<cr>', { noremap = true, silent = true, desc = '/mnt/second/backup' })
vim.keymap.set('n', '<localleader><localleader>Hbk', function() require('mini.files').open('/mnt/second/backup') end, { noremap = true, silent = true, desc = '/mnt/second/backup' })
vim.keymap.set('c', ';Hdd', '/media/si/HDD<cr>', { noremap = true, silent = true, desc = '/media/si/HDD' })
vim.keymap.set('n', '<localleader><leader>Hdd', '<cmd>Explore /media/si/HDD<cr>', { noremap = true, silent = true, desc = '/media/si/HDD' })
vim.keymap.set('n', '<localleader><localleader>Hdd', function() require('mini.files').open('/media/si/HDD') end, { noremap = true, silent = true, desc = '/media/si/HDD' })
vim.keymap.set('c', ';Hfl', '/media/si/flash<cr>', { noremap = true, silent = true, desc = '/media/si/flash' })
vim.keymap.set('n', '<localleader><leader>Hfl', '<cmd>Explore /media/si/flash<cr>', { noremap = true, silent = true, desc = '/media/si/flash' })
vim.keymap.set('n', '<localleader><localleader>Hfl', function() require('mini.files').open('/media/si/flash') end, { noremap = true, silent = true, desc = '/media/si/flash' })
vim.keymap.set('c', ';Hme', '/media/si<cr>', { noremap = true, silent = true, desc = '/media/si' })
vim.keymap.set('n', '<localleader><leader>Hme', '<cmd>Explore /media/si<cr>', { noremap = true, silent = true, desc = '/media/si' })
vim.keymap.set('n', '<localleader><localleader>Hme', function() require('mini.files').open('/media/si') end, { noremap = true, silent = true, desc = '/media/si' })
vim.keymap.set('c', ';Hmt', '/mnt<cr>', { noremap = true, silent = true, desc = '/mnt' })
vim.keymap.set('n', '<localleader><leader>Hmt', '<cmd>Explore /mnt<cr>', { noremap = true, silent = true, desc = '/mnt' })
vim.keymap.set('n', '<localleader><localleader>Hmt', function() require('mini.files').open('/mnt') end, { noremap = true, silent = true, desc = '/mnt' })
vim.keymap.set('c', ';Hmw', '/usr/share/mutt-wizard<cr>', { noremap = true, silent = true, desc = '/usr/share/mutt-wizard' })
vim.keymap.set('n', '<localleader><leader>Hmw', '<cmd>Explore /usr/share/mutt-wizard<cr>', { noremap = true, silent = true, desc = '/usr/share/mutt-wizard' })
vim.keymap.set('n', '<localleader><localleader>Hmw', function() require('mini.files').open('/usr/share/mutt-wizard') end, { noremap = true, silent = true, desc = '/usr/share/mutt-wizard' })
vim.keymap.set('c', ';Hrr', '/run/runit/service<cr>', { noremap = true, silent = true, desc = '/run/runit/service' })
vim.keymap.set('n', '<localleader><leader>Hrr', '<cmd>Explore /run/runit/service<cr>', { noremap = true, silent = true, desc = '/run/runit/service' })
vim.keymap.set('n', '<localleader><localleader>Hrr', function() require('mini.files').open('/run/runit/service') end, { noremap = true, silent = true, desc = '/run/runit/service' })
vim.keymap.set('c', ';Hsc', '/mnt/second<cr>', { noremap = true, silent = true, desc = '/mnt/second' })
vim.keymap.set('n', '<localleader><leader>Hsc', '<cmd>Explore /mnt/second<cr>', { noremap = true, silent = true, desc = '/mnt/second' })
vim.keymap.set('n', '<localleader><localleader>Hsc', function() require('mini.files').open('/mnt/second') end, { noremap = true, silent = true, desc = '/mnt/second' })
vim.keymap.set('c', ';Hsg', '/media/si/storage/G<cr>', { noremap = true, silent = true, desc = '/media/si/storage/G' })
vim.keymap.set('n', '<localleader><leader>Hsg', '<cmd>Explore /media/si/storage/G<cr>', { noremap = true, silent = true, desc = '/media/si/storage/G' })
vim.keymap.set('n', '<localleader><localleader>Hsg', function() require('mini.files').open('/media/si/storage/G') end, { noremap = true, silent = true, desc = '/media/si/storage/G' })
vim.keymap.set('c', ';Hsm', '/media/si/samba<cr>', { noremap = true, silent = true, desc = '/media/si/samba' })
vim.keymap.set('n', '<localleader><leader>Hsm', '<cmd>Explore /media/si/samba<cr>', { noremap = true, silent = true, desc = '/media/si/samba' })
vim.keymap.set('n', '<localleader><localleader>Hsm', function() require('mini.files').open('/media/si/samba') end, { noremap = true, silent = true, desc = '/media/si/samba' })
vim.keymap.set('c', ';Hss', '/media/si/ssd<cr>', { noremap = true, silent = true, desc = '/media/si/ssd' })
vim.keymap.set('n', '<localleader><leader>Hss', '<cmd>Explore /media/si/ssd<cr>', { noremap = true, silent = true, desc = '/media/si/ssd' })
vim.keymap.set('n', '<localleader><localleader>Hss', function() require('mini.files').open('/media/si/ssd') end, { noremap = true, silent = true, desc = '/media/si/ssd' })
vim.keymap.set('c', ';Hst', '/media/si/storage<cr>', { noremap = true, silent = true, desc = '/media/si/storage' })
vim.keymap.set('n', '<localleader><leader>Hst', '<cmd>Explore /media/si/storage<cr>', { noremap = true, silent = true, desc = '/media/si/storage' })
vim.keymap.set('n', '<localleader><localleader>Hst', function() require('mini.files').open('/media/si/storage') end, { noremap = true, silent = true, desc = '/media/si/storage' })
vim.keymap.set('c', ';Hvt', '/media/si/Ventoy<cr>', { noremap = true, silent = true, desc = '/media/si/Ventoy' })
vim.keymap.set('n', '<localleader><leader>Hvt', '<cmd>Explore /media/si/Ventoy<cr>', { noremap = true, silent = true, desc = '/media/si/Ventoy' })
vim.keymap.set('n', '<localleader><localleader>Hvt', function() require('mini.files').open('/media/si/Ventoy') end, { noremap = true, silent = true, desc = '/media/si/Ventoy' })
vim.keymap.set('c', ';Hvv', '/mnt/second/videos<cr>', { noremap = true, silent = true, desc = '/mnt/second/videos' })
vim.keymap.set('n', '<localleader><leader>Hvv', '<cmd>Explore /mnt/second/videos<cr>', { noremap = true, silent = true, desc = '/mnt/second/videos' })
vim.keymap.set('n', '<localleader><localleader>Hvv', function() require('mini.files').open('/mnt/second/videos') end, { noremap = true, silent = true, desc = '/mnt/second/videos' })
vim.keymap.set('c', ';Hwv', '/media/si/win10/Videos<cr>', { noremap = true, silent = true, desc = '/media/si/win10/Videos' })
vim.keymap.set('n', '<localleader><leader>Hwv', '<cmd>Explore /media/si/win10/Videos<cr>', { noremap = true, silent = true, desc = '/media/si/win10/Videos' })
vim.keymap.set('n', '<localleader><localleader>Hwv', function() require('mini.files').open('/media/si/win10/Videos') end, { noremap = true, silent = true, desc = '/media/si/win10/Videos' })
vim.keymap.set('c', ';kdn', '/home/si/.local/share/kakaotalk/drive_c/users/si/Documents/카카오톡<cr>', { noremap = true, silent = true, desc = '~/.local/share/kakaotalk/drive_c/users/si/Documents/카카오톡' })
vim.keymap.set('n', '<localleader><leader>kdn', '<cmd>Explore /home/si/.local/share/kakaotalk/drive_c/users/si/Documents/카카오톡<cr>', { noremap = true, silent = true, desc = '~/.local/share/kakaotalk/drive_c/users/si/Documents/카카오톡' })
vim.keymap.set('n', '<localleader><localleader>kdn', function() require('mini.files').open('/home/si/.local/share/kakaotalk/drive_c/users/si/Documents/카카오톡') end, { noremap = true, silent = true, desc = '~/.local/share/kakaotalk/drive_c/users/si/Documents/카카오톡' })
vim.keymap.set('c', ';pae', '/home/si/.local/share/.password-store/exported_keys<cr>', { noremap = true, silent = true, desc = '~/.local/share/.password-store/exported_keys' })
vim.keymap.set('n', '<localleader><leader>pae', '<cmd>Explore /home/si/.local/share/.password-store/exported_keys<cr>', { noremap = true, silent = true, desc = '~/.local/share/.password-store/exported_keys' })
vim.keymap.set('n', '<localleader><localleader>pae', function() require('mini.files').open('/home/si/.local/share/.password-store/exported_keys') end, { noremap = true, silent = true, desc = '~/.local/share/.password-store/exported_keys' })
vim.keymap.set('c', ';pah', '/home/si/.local/share/.password-store/ssh<cr>', { noremap = true, silent = true, desc = '~/.local/share/.password-store/ssh' })
vim.keymap.set('n', '<localleader><leader>pah', '<cmd>Explore /home/si/.local/share/.password-store/ssh<cr>', { noremap = true, silent = true, desc = '~/.local/share/.password-store/ssh' })
vim.keymap.set('n', '<localleader><localleader>pah', function() require('mini.files').open('/home/si/.local/share/.password-store/ssh') end, { noremap = true, silent = true, desc = '~/.local/share/.password-store/ssh' })
vim.keymap.set('c', ';pas', '/home/si/.local/share/.password-store<cr>', { noremap = true, silent = true, desc = '~/.local/share/.password-store' })
vim.keymap.set('n', '<localleader><leader>pas', '<cmd>Explore /home/si/.local/share/.password-store<cr>', { noremap = true, silent = true, desc = '~/.local/share/.password-store' })
vim.keymap.set('n', '<localleader><localleader>pas', function() require('mini.files').open('/home/si/.local/share/.password-store') end, { noremap = true, silent = true, desc = '~/.local/share/.password-store' })
vim.keymap.set('c', ';pbg', '/home/si/Public/repos<cr>', { noremap = true, silent = true, desc = '~/Public/repos' })
vim.keymap.set('n', '<localleader><leader>pbg', '<cmd>Explore /home/si/Public/repos<cr>', { noremap = true, silent = true, desc = '~/Public/repos' })
vim.keymap.set('n', '<localleader><localleader>pbg', function() require('mini.files').open('/home/si/Public/repos') end, { noremap = true, silent = true, desc = '~/Public/repos' })
vim.keymap.set('c', ';pvg', '/home/si/Private/repos<cr>', { noremap = true, silent = true, desc = '~/Private/repos' })
vim.keymap.set('n', '<localleader><leader>pvg', '<cmd>Explore /home/si/Private/repos<cr>', { noremap = true, silent = true, desc = '~/Private/repos' })
vim.keymap.set('n', '<localleader><localleader>pvg', function() require('mini.files').open('/home/si/Private/repos') end, { noremap = true, silent = true, desc = '~/Private/repos' })
vim.keymap.set('c', ';pvn', '/home/si/Private/repos/neetcode<cr>', { noremap = true, silent = true, desc = '~/Private/repos/neetcode' })
vim.keymap.set('n', '<localleader><leader>pvn', '<cmd>Explore /home/si/Private/repos/neetcode<cr>', { noremap = true, silent = true, desc = '~/Private/repos/neetcode' })
vim.keymap.set('n', '<localleader><localleader>pvn', function() require('mini.files').open('/home/si/Private/repos/neetcode') end, { noremap = true, silent = true, desc = '~/Private/repos/neetcode' })
vim.keymap.set('c', ';pvo', '/home/si/Private/repos/Obsidian/SI<cr>', { noremap = true, silent = true, desc = '~/Private/repos/Obsidian/SI' })
vim.keymap.set('n', '<localleader><leader>pvo', '<cmd>Explore /home/si/Private/repos/Obsidian/SI<cr>', { noremap = true, silent = true, desc = '~/Private/repos/Obsidian/SI' })
vim.keymap.set('n', '<localleader><localleader>pvo', function() require('mini.files').open('/home/si/Private/repos/Obsidian/SI') end, { noremap = true, silent = true, desc = '~/Private/repos/Obsidian/SI' })
vim.keymap.set('c', ';pww', '/home/si/Private/photo<cr>', { noremap = true, silent = true, desc = '~/Private/photo' })
vim.keymap.set('n', '<localleader><leader>pww', '<cmd>Explore /home/si/Private/photo<cr>', { noremap = true, silent = true, desc = '~/Private/photo' })
vim.keymap.set('n', '<localleader><localleader>pww', function() require('mini.files').open('/home/si/Private/photo') end, { noremap = true, silent = true, desc = '~/Private/photo' })
vim.keymap.set('c', ';shm', '/home/si/.local/share/mail<cr>', { noremap = true, silent = true, desc = '~/.local/share/mail' })
vim.keymap.set('n', '<localleader><leader>shm', '<cmd>Explore /home/si/.local/share/mail<cr>', { noremap = true, silent = true, desc = '~/.local/share/mail' })
vim.keymap.set('n', '<localleader><localleader>shm', function() require('mini.files').open('/home/si/.local/share/mail') end, { noremap = true, silent = true, desc = '~/.local/share/mail' })
vim.keymap.set('c', ';shr', '/home/si/.local/share<cr>', { noremap = true, silent = true, desc = '~/.local/share' })
vim.keymap.set('n', '<localleader><leader>shr', '<cmd>Explore /home/si/.local/share<cr>', { noremap = true, silent = true, desc = '~/.local/share' })
vim.keymap.set('n', '<localleader><localleader>shr', function() require('mini.files').open('/home/si/.local/share') end, { noremap = true, silent = true, desc = '~/.local/share' })
vim.keymap.set('c', ';sk', '/home/si/.local/src/suckless<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless' })
vim.keymap.set('n', '<localleader><leader>sk', '<cmd>Explore /home/si/.local/src/suckless<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless' })
vim.keymap.set('n', '<localleader><localleader>sk', function() require('mini.files').open('/home/si/.local/src/suckless') end, { noremap = true, silent = true, desc = '~/.local/src/suckless' })
vim.keymap.set('c', ';slr', '/home/si/.local/share/lyrics<cr>', { noremap = true, silent = true, desc = '~/.local/share/lyrics' })
vim.keymap.set('n', '<localleader><leader>slr', '<cmd>Explore /home/si/.local/share/lyrics<cr>', { noremap = true, silent = true, desc = '~/.local/share/lyrics' })
vim.keymap.set('n', '<localleader><localleader>slr', function() require('mini.files').open('/home/si/.local/share/lyrics') end, { noremap = true, silent = true, desc = '~/.local/share/lyrics' })
vim.keymap.set('c', ';sr', '/home/si/.local/src<cr>', { noremap = true, silent = true, desc = '~/.local/src' })
vim.keymap.set('n', '<localleader><leader>sr', '<cmd>Explore /home/si/.local/src<cr>', { noremap = true, silent = true, desc = '~/.local/src' })
vim.keymap.set('n', '<localleader><localleader>sr', function() require('mini.files').open('/home/si/.local/src') end, { noremap = true, silent = true, desc = '~/.local/src' })
vim.keymap.set('c', ';tk', '/home/si/.local/share/thesiah/keys<cr>', { noremap = true, silent = true, desc = '~/.local/share/thesiah/keys' })
vim.keymap.set('n', '<localleader><leader>tk', '<cmd>Explore /home/si/.local/share/thesiah/keys<cr>', { noremap = true, silent = true, desc = '~/.local/share/thesiah/keys' })
vim.keymap.set('n', '<localleader><localleader>tk', function() require('mini.files').open('/home/si/.local/share/thesiah/keys') end, { noremap = true, silent = true, desc = '~/.local/share/thesiah/keys' })
vim.keymap.set('c', ';tr', '/home/si/.local/share/Trash/files<cr>', { noremap = true, silent = true, desc = '~/.local/share/Trash/files' })
vim.keymap.set('n', '<localleader><leader>tr', '<cmd>Explore /home/si/.local/share/Trash/files<cr>', { noremap = true, silent = true, desc = '~/.local/share/Trash/files' })
vim.keymap.set('n', '<localleader><localleader>tr', function() require('mini.files').open('/home/si/.local/share/Trash/files') end, { noremap = true, silent = true, desc = '~/.local/share/Trash/files' })
vim.keymap.set('c', ';ts', '/home/si/.local/share/thesiah<cr>', { noremap = true, silent = true, desc = '~/.local/share/thesiah' })
vim.keymap.set('n', '<localleader><leader>ts', '<cmd>Explore /home/si/.local/share/thesiah<cr>', { noremap = true, silent = true, desc = '~/.local/share/thesiah' })
vim.keymap.set('n', '<localleader><localleader>ts', function() require('mini.files').open('/home/si/.local/share/thesiah') end, { noremap = true, silent = true, desc = '~/.local/share/thesiah' })
vim.keymap.set('c', ';tt', '/home/si/.local/state<cr>', { noremap = true, silent = true, desc = '~/.local/state' })
vim.keymap.set('n', '<localleader><leader>tt', '<cmd>Explore /home/si/.local/state<cr>', { noremap = true, silent = true, desc = '~/.local/state' })
vim.keymap.set('n', '<localleader><localleader>tt', function() require('mini.files').open('/home/si/.local/state') end, { noremap = true, silent = true, desc = '~/.local/state' })
vim.keymap.set('c', ';vwk', '/home/si/.local/share/vimwiki<cr>', { noremap = true, silent = true, desc = '~/.local/share/vimwiki' })
vim.keymap.set('n', '<localleader><leader>vwk', '<cmd>Explore /home/si/.local/share/vimwiki<cr>', { noremap = true, silent = true, desc = '~/.local/share/vimwiki' })
vim.keymap.set('n', '<localleader><localleader>vwk', function() require('mini.files').open('/home/si/.local/share/vimwiki') end, { noremap = true, silent = true, desc = '~/.local/share/vimwiki' })
vim.keymap.set('c', ';vww', '/home/si/.wallpapers/video<cr>', { noremap = true, silent = true, desc = '~/.wallpapers/video' })
vim.keymap.set('n', '<localleader><leader>vww', '<cmd>Explore /home/si/.wallpapers/video<cr>', { noremap = true, silent = true, desc = '~/.wallpapers/video' })
vim.keymap.set('n', '<localleader><localleader>vww', function() require('mini.files').open('/home/si/.wallpapers/video') end, { noremap = true, silent = true, desc = '~/.wallpapers/video' })
vim.keymap.set('c', ';web', '/home/si/Private/repos/THESIAH<cr>', { noremap = true, silent = true, desc = '~/Private/repos/THESIAH' })
vim.keymap.set('n', '<localleader><leader>web', '<cmd>Explore /home/si/Private/repos/THESIAH<cr>', { noremap = true, silent = true, desc = '~/Private/repos/THESIAH' })
vim.keymap.set('n', '<localleader><localleader>web', function() require('mini.files').open('/home/si/Private/repos/THESIAH') end, { noremap = true, silent = true, desc = '~/Private/repos/THESIAH' })
vim.keymap.set('c', ';wep', '/home/si/Private/repos/THESIAH/public<cr>', { noremap = true, silent = true, desc = '~/Private/repos/THESIAH/public' })
vim.keymap.set('n', '<localleader><leader>wep', '<cmd>Explore /home/si/Private/repos/THESIAH/public<cr>', { noremap = true, silent = true, desc = '~/Private/repos/THESIAH/public' })
vim.keymap.set('n', '<localleader><localleader>wep', function() require('mini.files').open('/home/si/Private/repos/THESIAH/public') end, { noremap = true, silent = true, desc = '~/Private/repos/THESIAH/public' })
vim.keymap.set('c', ';wes', '/home/si/Private/repos/THESIAH/static<cr>', { noremap = true, silent = true, desc = '~/Private/repos/THESIAH/static' })
vim.keymap.set('n', '<localleader><leader>wes', '<cmd>Explore /home/si/Private/repos/THESIAH/static<cr>', { noremap = true, silent = true, desc = '~/Private/repos/THESIAH/static' })
vim.keymap.set('n', '<localleader><localleader>wes', function() require('mini.files').open('/home/si/Private/repos/THESIAH/static') end, { noremap = true, silent = true, desc = '~/Private/repos/THESIAH/static' })
vim.keymap.set('c', ';vab', '/home/si/.config/abook/addressbook<cr>', { noremap = true, silent = true, desc = '~/.config/abook/addressbook' })
vim.keymap.set('n', '<localleader><localleader>vab', '<cmd>e /home/si/.config/abook/addressbook<cr>', { noremap = true, silent = true, desc = '~/.config/abook/addressbook' })
vim.keymap.set('c', ';vbc', '/home/si/.config/bash/bashrc<cr>', { noremap = true, silent = true, desc = '~/.config/bash/bashrc' })
vim.keymap.set('n', '<localleader><localleader>vbc', '<cmd>e /home/si/.config/bash/bashrc<cr>', { noremap = true, silent = true, desc = '~/.config/bash/bashrc' })
vim.keymap.set('c', ';vbd', '/home/si/.config/shell/bm-dirs<cr>', { noremap = true, silent = true, desc = '~/.config/shell/bm-dirs' })
vim.keymap.set('n', '<localleader><localleader>vbd', '<cmd>e /home/si/.config/shell/bm-dirs<cr>', { noremap = true, silent = true, desc = '~/.config/shell/bm-dirs' })
vim.keymap.set('c', ';vbf', '/home/si/.config/shell/bm-files<cr>', { noremap = true, silent = true, desc = '~/.config/shell/bm-files' })
vim.keymap.set('n', '<localleader><localleader>vbf', '<cmd>e /home/si/.config/shell/bm-files<cr>', { noremap = true, silent = true, desc = '~/.config/shell/bm-files' })
vim.keymap.set('c', ';vbi', '/home/si/.config/shell/inputrc<cr>', { noremap = true, silent = true, desc = '~/.config/shell/inputrc' })
vim.keymap.set('n', '<localleader><localleader>vbi', '<cmd>e /home/si/.config/shell/inputrc<cr>', { noremap = true, silent = true, desc = '~/.config/shell/inputrc' })
vim.keymap.set('c', ';vbp', '/home/si/.config/bash/bash_profile<cr>', { noremap = true, silent = true, desc = '~/.config/bash/bash_profile' })
vim.keymap.set('n', '<localleader><localleader>vbp', '<cmd>e /home/si/.config/bash/bash_profile<cr>', { noremap = true, silent = true, desc = '~/.config/bash/bash_profile' })
vim.keymap.set('c', ';vcr', '/home/si/.dotfiles/ar/.config/crons<cr>', { noremap = true, silent = true, desc = '~/.dotfiles/ar/.config/crons' })
vim.keymap.set('n', '<localleader><localleader>vcr', '<cmd>e /home/si/.dotfiles/ar/.config/crons<cr>', { noremap = true, silent = true, desc = '~/.dotfiles/ar/.config/crons' })
vim.keymap.set('c', ';vdb', '/home/si/.local/src/suckless/dwmblocks/config.h<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/dwmblocks/config.h' })
vim.keymap.set('n', '<localleader><localleader>vdb', '<cmd>e /home/si/.local/src/suckless/dwmblocks/config.h<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/dwmblocks/config.h' })
vim.keymap.set('c', ';vdm', '/home/si/.local/src/suckless/dmenu/config.h<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/dmenu/config.h' })
vim.keymap.set('n', '<localleader><localleader>vdm', '<cmd>e /home/si/.local/src/suckless/dmenu/config.h<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/dmenu/config.h' })
vim.keymap.set('c', ';vdw', '/home/si/.local/src/suckless/dwm/config.h<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/dwm/config.h' })
vim.keymap.set('n', '<localleader><localleader>vdw', '<cmd>e /home/si/.local/src/suckless/dwm/config.h<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/dwm/config.h' })
vim.keymap.set('c', ';vgc', '/home/si/.config/shell/git-aliasrc<cr>', { noremap = true, silent = true, desc = '~/.config/shell/git-aliasrc' })
vim.keymap.set('n', '<localleader><localleader>vgc', '<cmd>e /home/si/.config/shell/git-aliasrc<cr>', { noremap = true, silent = true, desc = '~/.config/shell/git-aliasrc' })
vim.keymap.set('c', ';vlf', '/home/si/.config/lf/lfrc<cr>', { noremap = true, silent = true, desc = '~/.config/lf/lfrc' })
vim.keymap.set('n', '<localleader><localleader>vlf', '<cmd>e /home/si/.config/lf/lfrc<cr>', { noremap = true, silent = true, desc = '~/.config/lf/lfrc' })
vim.keymap.set('c', ';vls', '/home/si/.config/lf/scope<cr>', { noremap = true, silent = true, desc = '~/.config/lf/scope' })
vim.keymap.set('n', '<localleader><localleader>vls', '<cmd>e /home/si/.config/lf/scope<cr>', { noremap = true, silent = true, desc = '~/.config/lf/scope' })
vim.keymap.set('c', ';vly', '/home/si/.lynxrc<cr>', { noremap = true, silent = true, desc = '~/.lynxrc' })
vim.keymap.set('n', '<localleader><localleader>vly', '<cmd>e /home/si/.lynxrc<cr>', { noremap = true, silent = true, desc = '~/.lynxrc' })
vim.keymap.set('c', ';vmw', '/home/si/.config/mutt/muttrc<cr>', { noremap = true, silent = true, desc = '~/.config/mutt/muttrc' })
vim.keymap.set('n', '<localleader><localleader>vmw', '<cmd>e /home/si/.config/mutt/muttrc<cr>', { noremap = true, silent = true, desc = '~/.config/mutt/muttrc' })
vim.keymap.set('c', ';Vmw', '/usr/share/mutt-wizard/mutt-wizard.muttrc<cr>', { noremap = true, silent = true, desc = '/usr/share/mutt-wizard/mutt-wizard.muttrc' })
vim.keymap.set('n', '<localleader><localleader>Vmw', '<cmd>e /usr/share/mutt-wizard/mutt-wizard.muttrc<cr>', { noremap = true, silent = true, desc = '/usr/share/mutt-wizard/mutt-wizard.muttrc' })
vim.keymap.set('c', ';vnb', '/home/si/.config/ncmpcpp/bindings<cr>', { noremap = true, silent = true, desc = '~/.config/ncmpcpp/bindings' })
vim.keymap.set('n', '<localleader><localleader>vnb', '<cmd>e /home/si/.config/ncmpcpp/bindings<cr>', { noremap = true, silent = true, desc = '~/.config/ncmpcpp/bindings' })
vim.keymap.set('c', ';vnc', '/home/si/.config/ncmpcpp/config<cr>', { noremap = true, silent = true, desc = '~/.config/ncmpcpp/config' })
vim.keymap.set('n', '<localleader><localleader>vnc', '<cmd>e /home/si/.config/ncmpcpp/config<cr>', { noremap = true, silent = true, desc = '~/.config/ncmpcpp/config' })
vim.keymap.set('c', ';vns', '/home/si/.config/newsboat/config<cr>', { noremap = true, silent = true, desc = '~/.config/newsboat/config' })
vim.keymap.set('n', '<localleader><localleader>vns', '<cmd>e /home/si/.config/newsboat/config<cr>', { noremap = true, silent = true, desc = '~/.config/newsboat/config' })
vim.keymap.set('c', ';vnu', '/home/si/.config/newsboat/urls<cr>', { noremap = true, silent = true, desc = '~/.config/newsboat/urls' })
vim.keymap.set('n', '<localleader><localleader>vnu', '<cmd>e /home/si/.config/newsboat/urls<cr>', { noremap = true, silent = true, desc = '~/.config/newsboat/urls' })
vim.keymap.set('c', ';Vsm', '/etc/samba/smb.conf<cr>', { noremap = true, silent = true, desc = '/etc/samba/smb.conf' })
vim.keymap.set('n', '<localleader><localleader>Vsm', '<cmd>e /etc/samba/smb.conf<cr>', { noremap = true, silent = true, desc = '/etc/samba/smb.conf' })
vim.keymap.set('c', ';vse', '/home/si/.config/sesh/sesh.toml<cr>', { noremap = true, silent = true, desc = '~/.config/sesh/sesh.toml' })
vim.keymap.set('n', '<localleader><localleader>vse', '<cmd>e /home/si/.config/sesh/sesh.toml<cr>', { noremap = true, silent = true, desc = '~/.config/sesh/sesh.toml' })
vim.keymap.set('c', ';vsl', '/home/si/.local/src/suckless/slock/config.h<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/slock/config.h' })
vim.keymap.set('n', '<localleader><localleader>vsl', '<cmd>e /home/si/.local/src/suckless/slock/config.h<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/slock/config.h' })
vim.keymap.set('c', ';vsp', '/home/si/.local/share/thesiah/snippets<cr>', { noremap = true, silent = true, desc = '~/.local/share/thesiah/snippets' })
vim.keymap.set('n', '<localleader><localleader>vsp', '<cmd>e /home/si/.local/share/thesiah/snippets<cr>', { noremap = true, silent = true, desc = '~/.local/share/thesiah/snippets' })
vim.keymap.set('c', ';vss', '/home/si/.config/starship/starship.toml<cr>', { noremap = true, silent = true, desc = '~/.config/starship/starship.toml' })
vim.keymap.set('n', '<localleader><localleader>vss', '<cmd>e /home/si/.config/starship/starship.toml<cr>', { noremap = true, silent = true, desc = '~/.config/starship/starship.toml' })
vim.keymap.set('c', ';vst', '/home/si/.local/src/suckless/st/config.h<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/st/config.h' })
vim.keymap.set('n', '<localleader><localleader>vst', '<cmd>e /home/si/.local/src/suckless/st/config.h<cr>', { noremap = true, silent = true, desc = '~/.local/src/suckless/st/config.h' })
vim.keymap.set('c', ';vsx', '/home/si/.config/nsxiv/exec/key-handler<cr>', { noremap = true, silent = true, desc = '~/.config/nsxiv/exec/key-handler' })
vim.keymap.set('n', '<localleader><localleader>vsx', '<cmd>e /home/si/.config/nsxiv/exec/key-handler<cr>', { noremap = true, silent = true, desc = '~/.config/nsxiv/exec/key-handler' })
vim.keymap.set('c', ';vtc', '/home/si/.config/task/taskrc<cr>', { noremap = true, silent = true, desc = '~/.config/task/taskrc' })
vim.keymap.set('n', '<localleader><localleader>vtc', '<cmd>e /home/si/.config/task/taskrc<cr>', { noremap = true, silent = true, desc = '~/.config/task/taskrc' })
vim.keymap.set('c', ';vtm', '/home/si/.config/tmux/tmux.conf<cr>', { noremap = true, silent = true, desc = '~/.config/tmux/tmux.conf' })
vim.keymap.set('n', '<localleader><localleader>vtm', '<cmd>e /home/si/.config/tmux/tmux.conf<cr>', { noremap = true, silent = true, desc = '~/.config/tmux/tmux.conf' })
vim.keymap.set('c', ';vto', '/home/si/.config/taskopen/taskopenrc<cr>', { noremap = true, silent = true, desc = '~/.config/taskopen/taskopenrc' })
vim.keymap.set('n', '<localleader><localleader>vto', '<cmd>e /home/si/.config/taskopen/taskopenrc<cr>', { noremap = true, silent = true, desc = '~/.config/taskopen/taskopenrc' })
vim.keymap.set('c', ';vtt', '/home/si/.config/transmission-daemon/settings.json<cr>', { noremap = true, silent = true, desc = '~/.config/transmission-daemon/settings.json' })
vim.keymap.set('n', '<localleader><localleader>vtt', '<cmd>e /home/si/.config/transmission-daemon/settings.json<cr>', { noremap = true, silent = true, desc = '~/.config/transmission-daemon/settings.json' })
vim.keymap.set('c', ';vvc', '/home/si/.config/vim/vimrc<cr>', { noremap = true, silent = true, desc = '~/.config/vim/vimrc' })
vim.keymap.set('n', '<localleader><localleader>vvc', '<cmd>e /home/si/.config/vim/vimrc<cr>', { noremap = true, silent = true, desc = '~/.config/vim/vimrc' })
vim.keymap.set('c', ';vvi', '/home/si/.config/vim/init.vim<cr>', { noremap = true, silent = true, desc = '~/.config/vim/init.vim' })
vim.keymap.set('n', '<localleader><localleader>vvi', '<cmd>e /home/si/.config/vim/init.vim<cr>', { noremap = true, silent = true, desc = '~/.config/vim/init.vim' })
vim.keymap.set('c', ';vvp', '/home/si/.config/vim/plugins.vim<cr>', { noremap = true, silent = true, desc = '~/.config/vim/plugins.vim' })
vim.keymap.set('n', '<localleader><localleader>vvp', '<cmd>e /home/si/.config/vim/plugins.vim<cr>', { noremap = true, silent = true, desc = '~/.config/vim/plugins.vim' })
vim.keymap.set('c', ';vvw', '/home/si/.local/share/vimwiki<cr>', { noremap = true, silent = true, desc = '~/.local/share/vimwiki' })
vim.keymap.set('n', '<localleader><localleader>vvw', '<cmd>e /home/si/.local/share/vimwiki<cr>', { noremap = true, silent = true, desc = '~/.local/share/vimwiki' })
vim.keymap.set('c', ';vxc', '/home/si/.config/x11/xinitrc<cr>', { noremap = true, silent = true, desc = '~/.config/x11/xinitrc' })
vim.keymap.set('n', '<localleader><localleader>vxc', '<cmd>e /home/si/.config/x11/xinitrc<cr>', { noremap = true, silent = true, desc = '~/.config/x11/xinitrc' })
vim.keymap.set('c', ';vxp', '/home/si/.config/x11/xprofile<cr>', { noremap = true, silent = true, desc = '~/.config/x11/xprofile' })
vim.keymap.set('n', '<localleader><localleader>vxp', '<cmd>e /home/si/.config/x11/xprofile<cr>', { noremap = true, silent = true, desc = '~/.config/x11/xprofile' })
vim.keymap.set('c', ';vxr', '/home/si/.config/x11/xresources<cr>', { noremap = true, silent = true, desc = '~/.config/x11/xresources' })
vim.keymap.set('n', '<localleader><localleader>vxr', '<cmd>e /home/si/.config/x11/xresources<cr>', { noremap = true, silent = true, desc = '~/.config/x11/xresources' })
vim.keymap.set('c', ';vya', '/home/si/.config/youtube-viewer/api.json<cr>', { noremap = true, silent = true, desc = '~/.config/youtube-viewer/api.json' })
vim.keymap.set('n', '<localleader><localleader>vya', '<cmd>e /home/si/.config/youtube-viewer/api.json<cr>', { noremap = true, silent = true, desc = '~/.config/youtube-viewer/api.json' })
vim.keymap.set('c', ';vza', '/home/si/.config/shell/aliasrc<cr>', { noremap = true, silent = true, desc = '~/.config/shell/aliasrc' })
vim.keymap.set('n', '<localleader><localleader>vza', '<cmd>e /home/si/.config/shell/aliasrc<cr>', { noremap = true, silent = true, desc = '~/.config/shell/aliasrc' })
vim.keymap.set('c', ';vzc', '/home/si/.config/zsh/.zshrc<cr>', { noremap = true, silent = true, desc = '~/.config/zsh/.zshrc' })
vim.keymap.set('n', '<localleader><localleader>vzc', '<cmd>e /home/si/.config/zsh/.zshrc<cr>', { noremap = true, silent = true, desc = '~/.config/zsh/.zshrc' })
vim.keymap.set('c', ';vzk', '/home/si/.config/zsh/keymaps.zsh<cr>', { noremap = true, silent = true, desc = '~/.config/zsh/keymaps.zsh' })
vim.keymap.set('n', '<localleader><localleader>vzk', '<cmd>e /home/si/.config/zsh/keymaps.zsh<cr>', { noremap = true, silent = true, desc = '~/.config/zsh/keymaps.zsh' })
vim.keymap.set('c', ';vzp', '/home/si/.config/shell/profile<cr>', { noremap = true, silent = true, desc = '~/.config/shell/profile' })
vim.keymap.set('n', '<localleader><localleader>vzp', '<cmd>e /home/si/.config/shell/profile<cr>', { noremap = true, silent = true, desc = '~/.config/shell/profile' })
vim.keymap.set('c', ';vzs', '/home/si/.config/zsh/scripts.zsh<cr>', { noremap = true, silent = true, desc = '~/.config/zsh/scripts.zsh' })
vim.keymap.set('n', '<localleader><localleader>vzs', '<cmd>e /home/si/.config/zsh/scripts.zsh<cr>', { noremap = true, silent = true, desc = '~/.config/zsh/scripts.zsh' })
