#!/bin/bash

options=(
  style=square
  width=6.0
  hidpi=on
  active_color=0xff770000
  # active_color="gradient(top_left=0xffebeb99,bottom_right=0xfff57f17)"
  inactive_color=0xff444444
)

borders "${options[@]}"
