#!/bin/sh

if command -v kitty >/dev/null 2>&1; then
  printf '\033_Ga=d,d=a\033\\' >/dev/tty 2>/dev/null
  kitty +kitten icat --silent --stdin no --transfer-mode file --clear </dev/null >/dev/tty 2>/dev/null
fi
