customCommands:
  - key: "<c-a>"
    context: "global"
    command: "gh repo view --branch {{.CheckedOutBranch.Name}} --web"
    description: "Open current branch in browser"

  - key: "<c-p>"
    context: "global"
    command: "gh pr view --web"
    description: "Open current PR in browser"

  - key: "H"
    context: "commits"
    command: "git push home master"
    description: "Push to home remote"
    prompts:
      - type: "confirm"
        title: "Push to remote"
        body: "Are you sure you want to push to the remote?"
