#!/bin/sh

xrandr --auto --dpi 96 # adjust the number based on your resolution and size of the screen

setbg &  # set the background with the `setbg` script
fcitx5 & # set the input method

# Uncomment to use Xresources colors/settings on startup
# xrdb "${XDG_CONFIG_HOME:-${HOME}/.config}/x11/xresources" &
# xrdbpid=$!

autostart="mpd xcompmgr dunst unclutter pipewire blueman-applet remapd"

for program in $autostart; do
  pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
