music_directory         "~/Music"
playlist_directory      "~/.config/mpd/playlists"
sticker_file            "~/.cache/mpd/sticker.sql"
db_file                 "~/.cache/mpd/database"
state_file              "~/.cache/mpd/state"
log_file                "~/.cache/mpd/mpd.log"

auto_update             "yes"
bind_to_address         "127.0.0.1"
restore_paused          "yes"
max_output_buffer_size  "16384"

audio_output {
  type "osx"
  name "CoreAudio"
}

audio_output {
  type    "fifo"
  name    "Visualizer feed"
  path    "/tmp/mpd.fifo"
  format  "44100:16:2"
}
