sort_order = [
  "tmuxinator", # show first
  "tmux",
  "config",
  "zoxide", # show last
]

[default_session]
startup_command = "if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then git status; else clear && ls -I .git; fi"
preview_command = "eza -glaa --icons --group-directories-first --color=always {}"

[[session]]
name = "code"
path = "~"
# disable_startup_command = true

[[session]]
name = "nvim config"
path = "~/.config/nvim"
startup_command = "nvim"

[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --plain --wrap character --color=always ~/.config/tmux/tmux.conf"

[[session]]
name = "config"
path = "~/.config"

[[session]]
name = "dotfiles"
path = "~/.dotfiles"

[[session]]
name = "private"
path = "~/Private"

[[session]]
name = "public"
path = "~/Public"

[[session]]
name = "scripts"
path = "~/.local/bin"

[[session]]
name = "suckless"
path = "~/.local/src/suckless"

[[window]]
name = "git"
startup_script = "git pull"
